# Generated by Django 5.2.13 on 2026-04-11 07:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=50, verbose_name='Название города')),
                ('postal_code', models.IntegerField(verbose_name='Почтовый индекс')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='complex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_complex', models.CharField(max_length=255, verbose_name='Название')),
                ('image_complex', models.ImageField(upload_to='images/startPage/complex/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Программный комлекс',
                'verbose_name_plural': 'Программные комлексы',
            },
        ),
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_contact', models.CharField(max_length=125, verbose_name='Имя пользователя')),
                ('email_contact', models.EmailField(max_length=254, verbose_name='Электронная почта пользователя')),
                ('text_contact', models.TextField(max_length=350, verbose_name='Сообщение пользователя')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(max_length=10, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='inst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_instruction', models.CharField(max_length=64, verbose_name='Название инструктажа')),
                ('date_period', models.IntegerField(verbose_name='Период инструктажа')),
            ],
            options={
                'verbose_name': 'Инструктаж',
                'verbose_name_plural': 'Инструктажи',
            },
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Вопрос создан')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_region', models.CharField(max_length=64, verbose_name='Название Региона')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_role', models.CharField(max_length=30, verbose_name='Название роли')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_special', models.CharField(max_length=255, verbose_name='Название специальности')),
                ('encryption_special', models.CharField(max_length=10, verbose_name='Шифр специальности')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_street', models.CharField(max_length=64, verbose_name='Название улицы')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'Улицы',
            },
        ),
        migrations.CreateModel(
            name='typeuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type_user', models.CharField(max_length=15, verbose_name='Название типа пользователя')),
            ],
            options={
                'verbose_name': 'Тип пользователя',
                'verbose_name_plural': 'Тип пользователей',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('patronymic', models.CharField(max_length=250, verbose_name='Отчество')),
                ('gender', models.CharField(choices=[('m', 'Мужской'), ('j', 'Женский')], max_length=3, null=True, verbose_name='Пол')),
                ('birthday_date', models.DateField(null=True, verbose_name='Дата рождения')),
                ('house', models.IntegerField(null=True, verbose_name='Номер дома')),
                ('flat', models.IntegerField(null=True, verbose_name='Этаж')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/users/', verbose_name='Изображение пользователя')),
                ('phone_number', models.CharField(max_length=20, null=True, unique=True, verbose_name='Номер телефона')),
                ('date_end', models.DateField(null=True, verbose_name='Дата завершения зачисления')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='region', chained_model_field='region', null=True, on_delete=django.db.models.deletion.CASCADE, to='initru.city', verbose_name='Город')),
                ('groupStud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='initru.groups', verbose_name='Группа')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='initru.region', verbose_name='Регион')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='initru.role', verbose_name='Роль')),
                ('street', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='initru.street', verbose_name='Улица')),
                ('type_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='initru.typeuser', verbose_name='Тип пользователя')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400, verbose_name='Ответ')),
                ('correct', models.BooleanField(default=False, verbose_name='Правильный или нет')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initru.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initru.region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='groups',
            name='special',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initru.spec', verbose_name='Специальность'),
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_test', models.CharField(max_length=125, verbose_name='Название теста инструктажа')),
                ('number_of_questions', models.IntegerField(verbose_name='Количество вопросов')),
                ('time', models.IntegerField(verbose_name='Ограничение по времени')),
                ('required_score_to_pass', models.IntegerField(help_text='Рекомендуемый балл в %', verbose_name='Рекомендуемый балл в %')),
                ('file', models.FileField(blank=True, null=True, upload_to='instr/', verbose_name='Файл к тесту')),
                ('date_target', models.DateTimeField(verbose_name='Дата назначения')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initru.inst', verbose_name='Инструктаж')),
                ('stud_groups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='initru.groups', verbose_name='Группа')),
                ('type_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initru.typeuser', verbose_name='Тип пользователя')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='res',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_instruction', models.DateTimeField(verbose_name='Дата прохождения инструктажа')),
                ('date_instruction_end', models.IntegerField(null=True, verbose_name='Прошло дней')),
                ('result', models.IntegerField(verbose_name='Результат в %')),
                ('mark', models.CharField(max_length=255, verbose_name='Прошел')),
                ('attempt', models.IntegerField(verbose_name='Количество попыток прохождения')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initru.inst', verbose_name='Инструктаж')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initru.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initru.test', verbose_name='Номер теста'),
        ),
        migrations.CreateModel(
            name='downloadInstructionsForTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initru.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Сводная по скачанным файлам',
                'verbose_name_plural': 'Сводная по скачанным файлам',
            },
        ),
        migrations.CreateModel(
            name='briefsForPeoples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_target', models.DateTimeField(verbose_name='Время назначения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t', to='initru.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Назначенные тесты отдельным пользователям',
                'verbose_name_plural': 'Назначенные тесты отдельным пользователям',
            },
        ),
    ]
