# Generated by Django 4.1.2 on 2023-01-18 14:07

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(help_text='Введите имя', max_length=150, verbose_name='Имя')),
                ('patronymic', models.CharField(help_text='Введите Отчество', max_length=250, verbose_name='Отчество')),
                ('gender', models.CharField(choices=[('m', 'Мужской'), ('j', 'Женский')], max_length=3, verbose_name='Пол')),
                ('birthday_date', models.DateField(verbose_name='Дата рождения')),
                ('house', models.IntegerField(verbose_name='Номер дома')),
                ('flat', models.IntegerField(verbose_name='Этаж')),
                ('avatar', models.ImageField(null=True, upload_to='users/%Y/%m/%d')),
                ('date_start', models.DateField(auto_now_add=True, verbose_name='Дата назначения')),
                ('date_end', models.DateField(verbose_name='Дата завершения')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(help_text='Введите электронную почту', max_length=254, unique=True, verbose_name='Электронная почта')),
                ('date_joined', models.DateTimeField(null=True, verbose_name='Дата вступления')),
                ('username', models.CharField(help_text='Введите логин', max_length=150, unique=True, verbose_name='Логин')),
                ('password', models.CharField(help_text='Введите пароль', max_length=128, verbose_name='Пароль')),
                ('is_staff', models.BooleanField(verbose_name='Доступ к админ панели')),
                ('is_active', models.BooleanField(default=True, null=True, verbose_name='Активный')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='Последний вход')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Супер-пользователь')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='complex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_complex', models.CharField(max_length=255, verbose_name='Название')),
                ('image_complex', models.ImageField(upload_to='images/startPage/complex/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Программный комлекс',
                'verbose_name_plural': 'Программные комлексы',
            },
        ),
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_contact', models.CharField(max_length=125, verbose_name='Имя пользователя')),
                ('email_contact', models.EmailField(max_length=254, verbose_name='Электронная почта пользователя')),
                ('text_contact', models.TextField(max_length=350, verbose_name='Сообщение пользователя')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='inst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_instruction', models.CharField(max_length=64, verbose_name='Название инструктажа')),
                ('date_period', models.IntegerField(verbose_name='Период инструктажа')),
            ],
            options={
                'verbose_name': 'Инструктаж',
                'verbose_name_plural': 'Инструктажи',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_region', models.CharField(max_length=64, verbose_name='Название Региона')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_role', models.CharField(max_length=25, verbose_name='Название роли')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_special', models.CharField(max_length=255, verbose_name='Название специальности')),
                ('encryption_special', models.CharField(max_length=10, verbose_name='Шифр специальности')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_street', models.CharField(max_length=64, verbose_name='Название улицы')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'Улицы',
            },
        ),
        migrations.CreateModel(
            name='typeuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type_user', models.CharField(max_length=15, verbose_name='Название типа пользователя')),
            ],
            options={
                'verbose_name': 'Тип пользователя',
                'verbose_name_plural': 'Тип пользователей',
            },
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_test', models.CharField(max_length=125, verbose_name='Название вопрос')),
                ('instruction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initru.inst', verbose_name='Инструктаж')),
                ('type_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initru.typeuser', verbose_name='Тип пользователя')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='res',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_instruction', models.DateTimeField(verbose_name='Дата начала инструктажа')),
                ('result', models.IntegerField(verbose_name='Результат')),
                ('cause', models.CharField(max_length=255, verbose_name='Причина')),
                ('instruction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initru.inst', verbose_name='Инструктаж')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=64, verbose_name='Ответы')),
                ('score', models.IntegerField(verbose_name='балл')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initru.test', verbose_name='Номер теста')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(max_length=8, verbose_name='Название группы')),
                ('special_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initru.spec')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=50, verbose_name='Название города')),
                ('postal_code', models.IntegerField(verbose_name='Почтовый индекс')),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initru.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Балл')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initru.question', verbose_name='Вопрос')),
                ('result_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initru.res', verbose_name='Результат')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initru.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initru.groups', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initru.region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initru.role', verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='street_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initru.street', verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='type_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initru.typeuser', verbose_name='Тип пользователя'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
