# Generated by Django 4.1.5 on 2023-02-13 13:00

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('initru', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='result_id',
            new_name='result',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='region_id',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='groups',
            old_name='special_id',
            new_name='special',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='res',
            old_name='instruction_id',
            new_name='instruction',
        ),
        migrations.RenameField(
            model_name='res',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='instruction_id',
            new_name='instruction',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='type_user_id',
            new_name='type_user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='region_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='street_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='type_user_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='region', chained_model_field='region', null=True, on_delete=django.db.models.deletion.CASCADE, to='initru.city'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groupStud',
            field=models.ForeignKey(blank=True, help_text='Выберите группу', null=True, on_delete=django.db.models.deletion.CASCADE, to='initru.groups', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.ForeignKey(help_text='Выберите регион', null=True, on_delete=django.db.models.deletion.CASCADE, to='initru.region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(help_text='Выберите роль', null=True, on_delete=django.db.models.deletion.CASCADE, to='initru.role', verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='street',
            field=models.ForeignKey(help_text='Выберите регион', null=True, on_delete=django.db.models.deletion.CASCADE, to='initru.street', verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='type_user',
            field=models.ForeignKey(help_text='Выберите тип пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, to='initru.typeuser', verbose_name='Тип пользователя'),
        ),
        migrations.AddField(
            model_name='test',
            name='file',
            field=models.FileField(default=1, upload_to='instr/', verbose_name='Файл к тесту'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Загрузите фотографию', null=True, upload_to='images/users/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthday_date',
            field=models.DateField(help_text='Выберите дату', null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_end',
            field=models.DateField(help_text='Укажите дату', null=True, verbose_name='Дата завершения зачисления'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='flat',
            field=models.IntegerField(help_text='Введите значение', null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('m', 'Мужской'), ('j', 'Женский')], help_text='Выберите пол', max_length=3, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='house',
            field=models.IntegerField(help_text='Введите значение', null=True, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.FloatField(verbose_name='балл'),
        ),
        migrations.AlterField(
            model_name='test',
            name='name_test',
            field=models.CharField(max_length=125, verbose_name='Название теста инструктажа'),
        ),
    ]
