# Generated by Django 4.1.2 on 2023-03-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initru', '0002_rename_question_id_answers_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='times',
            field=models.IntegerField(default=1, verbose_name='Ограничение по времени'),
            preserve_default=False,
        ),
    ]
