# Generated by Django 4.1.5 on 2023-02-14 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initru', '0002_rename_question_id_answers_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/users/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthday_date',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_end',
            field=models.DateField(null=True, verbose_name='Дата завершения зачисления'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='flat',
            field=models.IntegerField(null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('m', 'Мужской'), ('j', 'Женский')], max_length=3, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groupStud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='initru.groups', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='house',
            field=models.IntegerField(null=True, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(max_length=250, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='initru.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='initru.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='street',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='initru.street', verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='initru.typeuser', verbose_name='Тип пользователя'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='special',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initru.spec', verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='test',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='instr/', verbose_name='Файл к тесту'),
        ),
    ]
