# Generated by Django 4.1.2 on 2023-03-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initru', '0003_alter_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.TextField(max_length=15, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
