# Generated by Django 4.1.2 on 2023-03-08 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initru', '0003_test_times'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='times',
            new_name='time',
        ),
    ]
