# Generated by Django 4.1.2 on 2023-03-08 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initru', '0005_rename_question_question_name_remove_answers_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='res',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='initru.test', verbose_name='Тест'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='res',
            name='date_instruction',
            field=models.DateTimeField(verbose_name='Дата прохождения инструктажа'),
        ),
    ]
