# Generated by Django 4.1.2 on 2023-03-08 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initru', '0006_res_quiz_alter_res_date_instruction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='res',
            old_name='cause',
            new_name='mark',
        ),
    ]
