# Generated by Django 4.1.2 on 2023-03-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initru', '0007_rename_cause_res_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.TextField(max_length=20, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
