# Generated by Django 4.1.2 on 2023-03-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initru', '0010_alter_res_mark_alter_res_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='text',
            field=models.CharField(max_length=400, verbose_name='Ответ'),
        ),
    ]
