# Generated by Django 4.1.2 on 2023-03-13 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initru', '0011_alter_answers_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='downloadInstructionsForTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initru.test', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сводная по скачанным файлам',
                'verbose_name_plural': 'Сводная по скачанным файлам',
            },
        ),
    ]
