# Generated by Django 4.1.2 on 2023-03-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initru', '0012_downloadinstructionsfortests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='file',
            field=models.FileField(blank=True, default='0', null=True, upload_to='instr/', verbose_name='Файл к тесту'),
        ),
    ]
