# Generated by Django 4.1.2 on 2023-03-17 16:59

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('initru', '0014_alter_test_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='res',
            name='date_instruction_end',
            field=models.DateTimeField(default='2004-01-19', verbose_name='Повторное прохождение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/users/', verbose_name='Изображение пользователя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='region', chained_model_field='region', null=True, on_delete=django.db.models.deletion.CASCADE, to='initru.city', verbose_name='Город'),
        ),
    ]
