# Generated by Django 4.1.2 on 2023-03-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initru', '0015_res_date_instruction_end_alter_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='res',
            name='date_instruction_end',
            field=models.DateTimeField(null=True, verbose_name='Повторное прохождение'),
        ),
    ]
