# Generated by Django 4.1.2 on 2023-03-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initru', '0016_alter_res_date_instruction_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='res',
            name='date_instruction_end',
            field=models.DateField(null=True, verbose_name='Повторное прохождение'),
        ),
    ]
