# Generated by Django 4.2 on 2023-04-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initru', '0017_alter_res_date_instruction_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name_role',
            field=models.CharField(max_length=30, verbose_name='Название роли'),
        ),
    ]
