# Generated by Django 4.2 on 2023-05-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initru', '0019_test_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='group',
        ),
    ]
