# Generated by Django 4.2 on 2023-05-02 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initru', '0020_remove_test_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='stud_groups',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='initru.groups', verbose_name='Группа'),
            preserve_default=False,
        ),
    ]
