# Generated by Django 4.2 on 2023-05-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initru', '0021_test_stud_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='date_target',
            field=models.DateField(default='2023-06-19', verbose_name='Дата назначения'),
            preserve_default=False,
        ),
    ]
