# Generated by Django 4.2 on 2023-05-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initru', '0022_test_date_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='res',
            name='date_instruction_end',
            field=models.DateField(null=True, verbose_name='Прошло дней'),
        ),
    ]
