# Generated by Django 4.2 on 2023-05-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initru', '0023_alter_res_date_instruction_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date_target',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения'),
        ),
    ]
