# Generated by Django 4.2 on 2023-05-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initru', '0025_alter_res_date_instruction_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='res',
            name='attempt',
            field=models.IntegerField(default=1, verbose_name='Количество попыток прохождения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groups',
            name='name_group',
            field=models.CharField(max_length=10, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='test',
            name='date_target',
            field=models.DateTimeField(verbose_name='Дата назначения'),
        ),
    ]
