# Generated by Django 4.2 on 2023-05-19 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initru', '0026_res_attempt_alter_groups_name_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='stud_groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='initru.groups', verbose_name='Группа'),
        ),
        migrations.CreateModel(
            name='briefsForPeoples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(verbose_name='Время назначения')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t', to='initru.test', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Назначенные тесты отдельным пользователям',
                'verbose_name_plural': 'Назначенные тесты отдельным пользователям',
            },
        ),
    ]
