# Generated by Django 4.2 on 2023-05-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initru', '0027_alter_test_stud_groups_briefsforpeoples'),
    ]

    operations = [
        migrations.RenameField(
            model_name='briefsforpeoples',
            old_name='date_start',
            new_name='date_target',
        ),
    ]
