# Generated by Django 4.2 on 2023-05-19 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initru', '0028_rename_date_start_briefsforpeoples_date_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='stud_groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='initru.groups', verbose_name='Группа'),
        ),
    ]
